### ISSUE TITLE
Provide one paragraph of text for profile site on about page

### ISSUE THREAD

**Issue by larnsce** [openwashdata/website#19]
@mianzg @sebastian-loos @mbannert 

I have prepared an About page for the website:

- preview: https://deploy-preview-18--luminous-treacle-bd685b.netlify.app/about

I would like to add a paragraph that highlights your involvement in openwashdata:

- example my page: https://deploy-preview-18--luminous-treacle-bd685b.netlify.app/about/lars/

@mbannert: I also need a photo from you :)

**Comment by mianzg** [comment]
@larnsce You can update me with LinkedIn: www.linkedin.com/in/mian-zhong-7aab10274

@mbannert We are still missing your picture and intro!

**Comment by mianzg** [comment]
@sskorik01 we will add you on the about page which you need to prepare a photo, a paragraph that highlights your involvement in openwashdata, and some social media profile you want to share (LinkedIn, GitHub, personal website etc)

**Comment by larnsce** [comment]
Preview is ready in PR: https://github.com/openwashdata/website/pull/33

@sskorik01: If you have anything else you want to add, let me know.

**Comment by larnsce** [comment]
@sskorik01: I have merged the page already. Can you please share:

- [ ] short paragraph about yourself
- [ ] any other profiles / webpages you want to have highlighted
- [ ] a profile photo
