### ISSUE TITLE
Add a glossary to the website which can also be used throughout other material

### ISSUE THREAD

**Issue by larnsce** [openwashdata/website#5]
# Resources

## glosario & related R Package 

- https://github.com/carpentries/glosario-r
- https://glosario.carpentries.org/
- https://twitter.com/gvwilson/status/1448013817259208713

## Glossaries

- FORRT: https://forrt.org/glossary/
- Teaching Tech Together: http://teachtogether.tech/en/index.html#s:gloss
- Open Data Handbook: https://opendatahandbook.org/glossary/en/
- Open Data Handbook Repo: https://github.com/okfn/opendatahandbook/tree/master/glossary
- RSE with Python: https://merely-useful.tech/py-rse/glossary.html#glossary
- The Turing Way: https://the-turing-way.netlify.app/afterword/glossary.html

**Comment by larnsce** [comment]
@mianzg @sebastian-loos @mbannert 

I have added the skeleton for a Glossary on the glossary branch of the website. I will use the same terms in a "data management strategy" book for our group.

https://github.com/Global-Health-Engineering/ghe-dms/blob/main/glossary.qmd

The concept is to be able to hyperlink the terms to the glossary using the (#term-id) throughout the text any time a term is used. I have tried to use the glosario-r package to access terms from the Carpentries glossary, but the package is currently broken.

**Glosario**

https://glosario.carpentries.org/
https://github.com/carpentries/glosario

**Concept**

https://github.com/quarto-dev/quarto-cli/issues/1697#issuecomment-1462441697

**Issue for broken package**

https://github.com/carpentries/glosario-r/issues/26

I would like to like external sources for definitions as much as possible. Good available glossaries to draw from are:

- https://opendatahandbook.org/glossary/en/
- https://forrt.org/glossary/
- http://teachtogether.tech/en/index.html#s:gloss
- https://merely-useful.tech/py-rse/glossary.html#glossary
- https://merely-useful.tech/py-rse/glossary.html#glossary
- https://the-turing-way.netlify.app/afterword/glossary.html

**Comment by mianzg** [comment]
The package error is due to some typos in its glossary.yml which I forked and fixed in my repo. Now this package could be used with the correct yml file.

The documentation is not clear to me how to combine quarto writing with this package.

**Comment by mianzg** [comment]
We also need to sort a list of terms that will appear in any launching articles and make sure they can be referred in our glossary.

**Comment by mianzg** [comment]
a good list to start: https://github.com/openwashdata/website/pull/13#issue-1819874733

**Comment by larnsce** [comment]
Another new resource for adding a glossary: https://debruine.github.io/quarto-glossary/

**Comment by larnsce** [comment]
Closing: the glossary skeleton is deployed on the website. Populating individual terms can be tracked separately if needed.
